# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'RssReaderWithRx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RssReaderWithRx
  pod 'FeedKit', '~> 6.0'

  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'

end
